### ISSUE TITLE
Compatible with civicrm 4.7?

### ISSUE THREAD

**Issue by alifrumin** [cividesk/com.cividesk.sync.googleapps#3]
Love the idea behind this extension. Do you guys have any plans to update it to work with civicrm 4.7?

**Comment by nganivet** [comment]
This extension is no longer working for new installs. The issues is not with CiviCRM, but with Google that has changed the way external programs can use their API. If you had generated an API token before it might still work, otherwise Google refuses to generate new API tokens as they have now moved to mandatory OAuth. The extension would need to be refactored to be compatible with OAuth, I am looking for sponsors in order to make this happen.

**Comment by alifrumin** [comment]
Thanks!

**Comment by mikaweinstein** [comment]
@nganivet Do you have a sense of how much it would cost to refactor it? We have a client who's potentially interested.

**Comment by nganivet** [comment]
@mikaweinstein Well, I have not really looked at it yet. I would imagine in the order of 3 to 5 days worth of work, but I would rather have a discussion with the interested party before providing a formal quote in order to make sure that expectations are clear and aligned: there are a number of limitations / particularities with Google Apps, so knowing more about the business case will help evaluate feasibility and costs.

**Comment by mikaweinstein** [comment]
@nganivet Thanks! I'll check in with them.

**Comment by andrimont** [comment]
@nganivet Waiting for a conversation w/ the interested party mentioned by @mikaweinstein  could you please indicate the change of status that is shown as _Stable_!
https://civicrm.org/extensions/google-apps-sync
That would be so kind to advise people not to test or install this extension as it not based on the OAuth2 provided by Google.
Thank you so much @nganivet.
And I hope that someone could take care to re-create this extension. I agree with @alifrumin about the service that such an extension could provide.

**Comment by nganivet** [comment]
@andrimont How is this a positive comment? I owe you nothing and you should be thanking me for producing this extension rather than throwing demands like this around. This extension works in 4.7 and is used on a daily basis by ourselves and a few of our clients, so it is in fact stable and will stay like this. Now if you don't like it you are welcome to pass your way in silence (and please don't go troll another open source developer).

**Comment by andrimont** [comment]
Very sorry @nganivet. The intention was to be positive, but that was not well expressed, you are right. 
As I misunderstood the issue brought by Google moving toward a mandatory OAuth and the impact on the extension, my point was not useful at all.
